### ISSUE TITLE
README 補上 Enviornment Variables 的使用方式

### ISSUE THREAD

**Issue by amowu** [hahow/hh-dotfiles#1]
`scripts/vimeo/path.sh` 其實已經可以設定 `VIMEO_ACCESS_TOKEN`，但是 README 沒有寫，所以新人會以為要自己設定。

**Comment by amowu** [comment]
後來發現 **Configuration** 的 **Enviornment Variables** 已經有附上檔案位置了。

**Comment by henry40408** [comment]
@amowu 缺 `WISTIA_API_PASSWORD`，雖然不一定用得到

**Comment by amowu** [comment]
@henry40408 已補上 https://github.com/hahow/hh-dotfiles/commit/2d270813ca9c22e825b0d8c41e0de949b2f1b477
